### PR TITLE
ign -> gz: rename files, change directories, create symlinks

### PR DESCRIPTION
**Pull request by j-rivero**
The PR replaces #109 and #112 and did three different changes:
 * 3af65ffa9031f7bd17a82e4e7c4d403d1e37b6bc Rename all files from ign- to gz-
 * 321e2d089f8a6a7bd66f8dfe3fc569f3459b065c Added ign- symlinks for previous files
 * 8a96b7c934b53516d94c12a46fd9070db67d69ab Change the checkout directories from ign- to gz- to match software new names

Tested [Build Status](https://build.osrfoundation.org/job/_test_ign_utils-ign-1-win/3/) together with https://github.com/gazebo-tooling/release-tools/pull/738

I was using the following commands:
```bash
# Rename files:
for f in $(ls ign-*.yaml); do git mv $f ${f/ign-/gz-}; done
for f in $(ls gz-gazebo*.yaml); do git mv $f ${f/gz-gazebo/gz-sim}; done
git ci --all -m "Rename files from ign- to gz-"
# symlinks for ignition
for f in $(ls gz-*.yaml); do ln -s $f ${f/gz-/ign-}; done
for f in $(ls ign-sim*.yaml); do mv $f ${f/ign-sim/ign-gazebo}; done
git add ign-*
git ci --all -m "Add ign- symlinks"
# Rename clone directories
sed -i 's/ign-\(.*\):/gz-\1:/g' collection-*.yaml gz-*.yaml sdformat-*.yaml
sed -i 's/gz-gazebo/gz-sim/g' collection-*.yaml gz-*.yaml
```

Caveats:
 * Although the symlinks are going to work on UNIX systems, Windows probably can no handle them correctly. 
 * The checkout directory is changing from ign- to gz- for the files named ign- so not real backward compat is done
 * I'm maintaining the checkout directories for Gazebo Classic

### CODE REVIEW

**Review by chapulina — APPROVED** [review]
LGTM, so just to summarize the breaking changes as I understand them:

Broken:

* Direct links to specific files, like https://raw.githubusercontent.com/gazebo-tooling/gazebodistro/master/ign-common5.yaml (i.e. https://raw.githubusercontent.com/gazebo-tooling/gazebodistro/jrivero/gz_migration/ign-common5.yaml)
* Logic that relies on the checkout directories (i.e. `cd ws/src/ign-gazebo`)

Not broken:

* Accessing specific files in UNIX after cloning `gazebodistro`, i.e. `git clone ...gazebodistro; cat ign-gazebo6.yaml`

I took a quick look at our docs and tooling, and I believe nothing will be affected by this besides Windows CI, which has a PR open to fix it. Most places are using the `collection-X.yaml` files and I don't think they're using the paths to each repo.

**Comment by j-rivero** [comment]
> LGTM, so just to summarize the breaking changes as I understand them:

correct as far as I can tell.
     
> I took a quick look at our docs and tooling, and I believe nothing will be affected by this besides Windows CI, which has a PR open to fix it. Most places are using the collection-X.yaml files and I don't think they're using the paths to each repo.

That is also my impression. Let's merge both PRs and fix anything that appear afterwards if any.

**Comment by chapulina** [comment]
Ok, we have our first failure, Windows CI for `ign-gazebo6`:

```
C:\Jenkins\workspace\ign_gazebo-pr-win>for /F %i in ('python "C:\Jenkins\workspace\ign_gazebo-pr-win\scripts\jenkins-scripts\\tools\detect_cmake_major_version.py" "C:\Jenkins\workspace\ign_gazebo-pr-win\gz-sim\CMakeLists.txt"') do set IGN_MAJOR_VERSION=%i 
Traceback (most recent call last):
  File "C:\Jenkins\workspace\ign_gazebo-pr-win\scripts\jenkins-scripts\\tools\detect_cmake_major_version.py", line 11, in <module>
    f = open(fileName, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Jenkins\\workspace\\ign_gazebo-pr-win\\gz-sim\\CMakeLists.txt'
7 was unexpected at this time.
```

https://build.osrfoundation.org/job/ign_gazebo-pr-win/4853/console

**Comment by j-rivero** [comment]
> Ok, we have our first failure, Windows CI for `ign-gazebo6`:

Umm I thought I have changed the DSL code yesterday playing with the PRs in release-tools. Somehow the changes were not done, fixing it now.

**Pull request merged**
