### PR TITLE
ign ➡️ gz

### PR DESCRIPTION
**Pull request by chapulina**
* Part of https://github.com/gazebo-tooling/release-tools/issues/698
* Builds on top of #111 

* For versions < Garden: update only repository URLs
* For Garden
    * URLs
    * Update directory names
    * Move `ign-*.yaml` to `gz-*.yaml`

### CODE REVIEW

**Comment by chapulina** [comment]
I started trying to fix Windows CI using this branch on https://github.com/gazebo-tooling/release-tools/compare/master...chapulina/gazebodistro_gz, but I'm starting to wonder if we shouldn't just move all files and change all directory names (even not Garden). 

Maintaining a single format will be easier in the long run. The downside is potentially breaking users of versions < Garden that rely on `gazebodistro` - but we've never promised this would be stable, so I think it may be worth the change.

Any thoughts, @j-rivero ?

**Comment by methylDragon** [comment]
LGTM! We'll need to remember to [gz-gazebo7.yaml](https://github.com/gazebo-tooling/gazebodistro/pull/109/files#diff-fff3d88be3b1bdaf5fecccfec57ffbb8d5d8b2393794d5c4482b9633f93ef9a8) -> `gz-sim7.yaml` once we migrate the project names though

**Review by methylDragon — APPROVED** [review]

**Comment by j-rivero** [comment]
> but I'm starting to wonder if we shouldn't just move all files and change all directory names (even not Garden).
> 
> Maintaining a single format will be easier in the long run. The downside is potentially breaking users of versions < Garden that rely on `gazebodistro` - but we've never promised this would be stable, so I think it may be worth the change.

I found the same blocker while testing https://github.com/gazebo-tooling/release-tools/pull/738 and https://github.com/gazebo-tooling/gazebodistro/pull/112. It would be great if we use the same names for all the files and at the same time maintain the current file names, something that we could probably accomplish on UNIX using symlinks. On Windows I would prefer to skip the symlink management so the option could be to duplicate the old files (previous to Garden) to have `ign-` and `gz-` with the obvious cost of maintenance and introducing a possible source of problems. I'm only proposing this since these files rarely change but I can be convinced otherwise.

**Comment by j-rivero** [comment]
Let's follow in #117

**Pull request closed without merging**
